import Head from "next/head";
import Image from "next/image";
import Cta from "../components/Cta";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import MoreInfoModal from "../components/MoreInfoModal";
import MoreInfo from "../components/MoreInfoModal";
import Navbar from "../components/Navbar";
import Map from "../components/Map";

import Values from "../components/Values";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Metaverse </title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        ></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <Values />

      <Map />
      <MoreInfoModal />
      <Cta />
      <Footer />
    </div>
  );
}
